export const CNST = {
    SET_COLOR_METHOD: {
        SUCCESS: "SET_COLOR_METHOD_SUCCESS"
    },
    SET_SVG_PATHS:{
        SUCCESS: "SET_SVG_PATHS_SUCCESS"
    },
    SET_COLORS_TO_SET:{
      SUCCESS: "SET_COLORS_TO_SET_SUCCESS"
    }
};
